#############################################################
# This ServiceNow-created file contains the path to the app in this repo
# path=<path to app content in your repo>
#############################################################
#
path=43b656ac3bdd8b1005ad7564c3e45a73
