import { Table, StringColumn, ReferenceColumn, IntegerColumn, DecimalColumn, BooleanColumn } from '@servicenow/sdk/core'

export const x_gegis_ins_policy_exposure_item = Table({
    name: 'x_gegis_ins_policy_exposure_item',
    label: 'Exposure Item',
    schema: {
        exposure_case: ReferenceColumn({
            label: 'Exposure case',
            referenceTable: 'x_gegis_ins_policy_exposure_case',
            mandatory: true,
        }),
        location: ReferenceColumn({
            label: 'Location',
            referenceTable: 'x_gegis_ins_policy_location',
        }),
        line_of_business: StringColumn({
            label: 'Line of business',
            mandatory: true,
            dropdown: 'dropdown_with_none',
            choices: {
                property: { label: 'Property', sequence: 0 },
                workers_comp: { label: 'Workers Comp', sequence: 1 },
                auto: { label: 'Auto', sequence: 2 },
            },
        }),
        building: DecimalColumn({ label: 'Building' }),
        machinery: DecimalColumn({ label: 'Machinery' }),
        pd_contents: DecimalColumn({ label: 'PD contents' }),
        stock: DecimalColumn({ label: 'Stock' }),
        stock_other_than_cio: DecimalColumn({ label: 'Stock other than CIO' }),
        pd_others: DecimalColumn({ label: 'PD others' }),
        physical_damage_total: DecimalColumn({ label: 'Physical damage total' }),
        business_interruption_total: DecimalColumn({ label: 'BI total' }),
        sum_insured: DecimalColumn({ label: 'Sum insured' }),
        others_bi_values: DecimalColumn({ label: 'Others BI values' }),
        indemnity_period_months: IntegerColumn({ label: 'Indemnity period (months)' }),
        payroll_limitation: DecimalColumn({ label: 'Payroll limitation' }),
        extended_income_days: IntegerColumn({ label: 'Extended income days' }),
        civil_authority_waiting_period: IntegerColumn({ label: 'Civil authority wait (days)' }),
        dependent_props_waiting_period: IntegerColumn({ label: 'Dependent props wait (days)' }),
        utility_svc_waiting_period: IntegerColumn({ label: 'Utility svc wait (days)' }),
        bi_website_waiting_period: IntegerColumn({ label: 'BI website wait (days)' }),
        bpp: BooleanColumn({ label: 'Building & personal property' }),
        extra_expenses: DecimalColumn({ label: 'Extra expenses' }),
        earthquake: BooleanColumn({ label: 'Earthquake' }),
        flood: BooleanColumn({ label: 'Flood' }),
        national_flood_insurance: BooleanColumn({ label: 'National flood insurance' }),
        exclude_flood_from_bi: BooleanColumn({ label: 'Exclude flood from BI' }),
        equipment_breakdown_ext_rated: BooleanColumn({ label: 'Equip breakdown ext rated' }),
        hazardous_substance_limit: DecimalColumn({ label: 'Hazardous substance limit' }),
        spoilage_limit: DecimalColumn({ label: 'Spoilage limit' }),
        business_travel: BooleanColumn({ label: 'Business travel' }),
        electronic_vandalism_sublimit: DecimalColumn({ label: 'Electronic vandalism sublimit' }),
        crime_coverage: BooleanColumn({ label: 'Crime coverage' }),
        employee_theft_limit: DecimalColumn({ label: 'Employee theft limit' }),
        employee_theft_deductible: DecimalColumn({ label: 'Employee theft deductible' }),
        forgery_alteration_limit: DecimalColumn({ label: 'Forgery/alteration limit' }),
        computer_fund_transfer_fraud_limit: DecimalColumn({ label: 'Computer/fund transfer fraud' }),
        blanket_stock: BooleanColumn({ label: 'Require stock blanket limit' }),
        blanket_bpp_all_locations: BooleanColumn({ label: 'BPP blanket all locations' }),
        blanket_bi: BooleanColumn({ label: 'Require BI blanket limit' }),
        blanket_limitation_clause: BooleanColumn({ label: 'Blanket limitation clause' }),
        audit_period: StringColumn({ label: 'Audit period', maxLength: 50 }),
        currency: StringColumn({
            label: 'Currency',
            dropdown: 'dropdown_with_none',
            choices: {
                usd: { label: 'USD', sequence: 0 },
                gbp: { label: 'GBP', sequence: 1 },
                eur: { label: 'EUR', sequence: 2 },
                cad: { label: 'CAD', sequence: 3 },
                aud: { label: 'AUD', sequence: 4 },
                jpy: { label: 'JPY', sequence: 5 },
                chf: { label: 'CHF', sequence: 6 },
            },
        }),
    },
    allowWebServiceAccess: true,
    accessibleFrom: 'public',
    actions: ['read', 'update', 'delete', 'create'],
    index: [
        {
            name: 'index',
            unique: false,
            element: 'exposure_case',
        },
        {
            name: 'index2',
            unique: false,
            element: 'location',
        },
    ],
})
